// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package config

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6615c02eDecodeGithubComErupshisMetricsInternalAgentConfig(in *jlexer.Lexer, out *envConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Host":
			out.Host = string(in.String())
		case "ReportInterval":
			out.ReportInterval = string(in.String())
		case "PollInterval":
			out.PollInterval = string(in.String())
		case "RateLimit":
			out.RateLimit = string(in.String())
		case "Key":
			out.Key = string(in.String())
		case "CertRSA":
			out.CertRSA = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6615c02eEncodeGithubComErupshisMetricsInternalAgentConfig(out *jwriter.Writer, in envConfig) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Host\":"
		out.RawString(prefix[1:])
		out.String(string(in.Host))
	}
	{
		const prefix string = ",\"ReportInterval\":"
		out.RawString(prefix)
		out.String(string(in.ReportInterval))
	}
	{
		const prefix string = ",\"PollInterval\":"
		out.RawString(prefix)
		out.String(string(in.PollInterval))
	}
	{
		const prefix string = ",\"RateLimit\":"
		out.RawString(prefix)
		out.String(string(in.RateLimit))
	}
	{
		const prefix string = ",\"Key\":"
		out.RawString(prefix)
		out.String(string(in.Key))
	}
	{
		const prefix string = ",\"CertRSA\":"
		out.RawString(prefix)
		out.String(string(in.CertRSA))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v envConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6615c02eEncodeGithubComErupshisMetricsInternalAgentConfig(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v envConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6615c02eEncodeGithubComErupshisMetricsInternalAgentConfig(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *envConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6615c02eDecodeGithubComErupshisMetricsInternalAgentConfig(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *envConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6615c02eDecodeGithubComErupshisMetricsInternalAgentConfig(l, v)
}
func easyjson6615c02eDecodeGithubComErupshisMetricsInternalAgentConfig1(in *jlexer.Lexer, out *Config) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "address":
			out.Host = string(in.String())
		case "poll_interval":
			out.PollInterval, _ = time.ParseDuration(in.String())
		case "report_interval":
			out.ReportInterval, _ = time.ParseDuration(in.String())
		case "rate_limit":
			out.RateLimit = int64(in.Int64())
		case "hash_key":
			out.Key = string(in.String())
		case "crypto_key":
			out.CertRSA = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6615c02eEncodeGithubComErupshisMetricsInternalAgentConfig1(out *jwriter.Writer, in Config) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix[1:])
		out.String(string(in.Host))
	}
	{
		const prefix string = ",\"poll_interval\":"
		out.RawString(prefix)
		out.String(string(in.PollInterval.String()))
	}
	{
		const prefix string = ",\"report_interval\":"
		out.RawString(prefix)
		out.String(string(in.ReportInterval.String()))
	}
	{
		const prefix string = ",\"rate_limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.RateLimit))
	}
	{
		const prefix string = ",\"hash_key\":"
		out.RawString(prefix)
		out.String(string(in.Key))
	}
	{
		const prefix string = ",\"crypto_key\":"
		out.RawString(prefix)
		out.String(string(in.CertRSA))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Config) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6615c02eEncodeGithubComErupshisMetricsInternalAgentConfig1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Config) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6615c02eEncodeGithubComErupshisMetricsInternalAgentConfig1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Config) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6615c02eDecodeGithubComErupshisMetricsInternalAgentConfig1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Config) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6615c02eDecodeGithubComErupshisMetricsInternalAgentConfig1(l, v)
}
